listen_addresses = '*'
port = 5432
ssl = on
ssl_min_protocol_version = 'TLSv1.3'
ssl_cert_file = '/var/run/postgresql/pkc-tls/server.crt'
ssl_key_file = '/var/run/postgresql/pkc-tls/server.key'
ssl_ca_file = '/var/run/postgresql/pkc-tls/client-ca.crt'
password_encryption = 'scram-sha-256'
fsync = on
synchronous_commit = on
full_page_writes = on
shared_buffers = '192MB'
max_connections = 50
log_connections = on
log_disconnections = on
log_min_duration_statement = 1000
